auth1/core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

excursions/urls.py
from django.urls import path
from .views import *

app_name = 'excursions'

urlpatterns = [
    path('', home, name='home'),
]

i_evpatoria/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from excursions.admin import guide_site
from .views import *


urlpatterns = [
    path('', include('excursions.urls', namespace='excursions')),
    path('contacts', contacts, name='contacts'),
    path('users/', include('users.urls', namespace='users')),
    path('superadmin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('guide-admin/', guide_site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
                          
admin.site.index_title = 'Админка'
admin.site.site_header = 'Я-Евпатория!'
admin.site.site_title = 'Я-Евпатория!'

users/urls.py
from django.urls import path
from .views import UserProfileView, UpdateProfileView

app_name = 'users'


urlpatterns = [

    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path('<int:pk>/', UserProfileView.as_view(), name='profile'),
]

templates/partials/__navbar.html
<header class="border-t-4 border-blue-700 bg-white shadow-md">
    <nav class="container mx-auto px-4 flex items-center justify-between py-4" x-data="{ isOpen: false }">
        <div class="flex">
            <button
                    @click="isOpen = true">
                <svg fill="currentColor" viewBox="0 0 24 24" width="24" height="24">
                    <path class="heroicon-ui"
                          d="M4 5h16a1 1 0 010 2H4a1 1 0 110-2zm0 6h16a1 1 0 010 2H4a1 1 0 010-2zm0 6h16a1 1 0 010 2H4a1 1 0 010-2z"/>
                </svg>
            </button>

        </div>
        <div class="absolute top-0 left-0 bg-white border border-right h-full w-48" x-show="isOpen"
             @click.away="isOpen = false">
            <div class="flex justify-end">
                <button class="text-2xl mr-3 mt-1" @click="isOpen = false">&times;</button>
            </div>
            <ul>
                <li>
                    <a href="#" class="flex items-center px-3 py-3 hover:bg-gray-200">
                        <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                             height="24" class="text-gray-600">
                            <path d="M12 12a5 5 0 1 1 0-10 5 5 0 0 1 0 10zm0-2a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm9 11a1 1 0 0 1-2 0v-2a3 3 0 0 0-3-3H8a3 3 0 0 0-3 3v2a1 1 0 0 1-2 0v-2a5 5 0 0 1 5-5h8a5 5 0 0 1 5 5v2z"
                                  class="heroicon-ui"></path>
                        </svg>
                        <span class="ml-2">Account</span>
                    </a>
                </li>
                <li class="">
                    <a href="#" class="flex items-center px-3 py-3 hover:bg-gray-200">
                        <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24"
                             height="24" class="text-gray-600">
                            <path d="M9 4.58V4c0-1.1.9-2 2-2h2a2 2 0 0 1 2 2v.58a8 8 0 0 1 1.92 1.11l.5-.29a2 2 0 0 1 2.74.73l1 1.74a2 2 0 0 1-.73 2.73l-.5.29a8.06 8.06 0 0 1 0 2.22l.5.3a2 2 0 0 1 .73 2.72l-1 1.74a2 2 0 0 1-2.73.73l-.5-.3A8 8 0 0 1 15 19.43V20a2 2 0 0 1-2 2h-2a2 2 0 0 1-2-2v-.58a8 8 0 0 1-1.92-1.11l-.5.29a2 2 0 0 1-2.74-.73l-1-1.74a2 2 0 0 1 .73-2.73l.5-.29a8.06 8.06 0 0 1 0-2.22l-.5-.3a2 2 0 0 1-.73-2.72l1-1.74a2 2 0 0 1 2.73-.73l.5.3A8 8 0 0 1 9 4.57zM7.88 7.64l-.54.51-1.77-1.02-1 1.74 1.76 1.01-.17.73a6.02 6.02 0 0 0 0 2.78l.17.73-1.76 1.01 1 1.74 1.77-1.02.54.51a6 6 0 0 0 2.4 1.4l.72.2V20h2v-2.04l.71-.2a6 6 0 0 0 2.41-1.4l.54-.51 1.77 1.02 1-1.74-1.76-1.01.17-.73a6.02 6.02 0 0 0 0-2.78l-.17-.73 1.76-1.01-1-1.74-1.77 1.02-.54-.51a6 6 0 0 0-2.4-1.4l-.72-.2V4h-2v2.04l-.71.2a6 6 0 0 0-2.41 1.4zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"
                                  class="heroicon-ui"></path>
                        </svg>
                        <span class="ml-2">Settings</span>
                    </a>
                </li>
                <li>
                    <a href="#" class="flex items-center px-3 py-3 hover:bg-gray-200">
                        <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                             viewBox="0 0 24 24" class="text-gray-600">
                            <path d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M10.09 15.59L11.5 17l5-5-5-5-1.41 1.41L12.67 11H3v2h9.67l-2.58 2.59zM19 3H5c-1.11 0-2 .9-2 2v4h2V5h14v14H5v-4H3v4c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"></path>
                        </svg>
                        <span class="ml-2">Logout</span>
                    </a>
                </li>
            </ul>
        </div>

    </nav>
</header>

templates/partials/_navbar.html
<nav x-data="{ open: false }" class="bg-white shadow">
    <div class="max-w-full mx-auto px-2 sm:px-4 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex px-2 lg:px-0">
                <div class="flex-shrink-0 flex items-center">
                    {% if section == "excursions" %}
                        <img class="block h-10 lg:h-12 w-auto" src="/media/img/Я-Евпатория!.svg" alt="Workflow">
                    {% else %}
                        <a href="{% url 'excursions:home' %}"><img class="block h-10 lg:h-12 w-auto"
                                                                   src="/media/img/Я-Евпатория!.svg" alt="Workflow"></a>
                    {% endif %}
                </div>
                <div class="hidden lg:ml-6 lg:flex lg:space-x-8">
                    <!-- Current: "border-amber-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
                    <a href="{% url 'excursions:home' %}"
                       class="{% if section == "excursions" %} border-amber-500 text-gray-900 {% else %} border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 {% endif %} inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                        Экскурсии
                    </a>
                    <a href="{% url 'contacts' %}"
                       class="{% if section == "contacts" %} border-amber-500 text-gray-900 {% else %} border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 {% endif %} inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                        Контактная информация
                    </a>
                </div>
            </div>
            <div class="flex-1 flex items-center justify-center px-2 lg:ml-6 lg:justify-end">
                <div class="max-w-lg w-full lg:max-w-xs">
                    <label for="search" class="sr-only">Поиск</label>
                    <div class="relative">
                        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <svg class="h-5 w-5 text-gray-400" x-description="Heroicon name: solid/search"
                                 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                                 aria-hidden="true">
                                <path fill-rule="evenodd"
                                      d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                                      clip-rule="evenodd"></path>
                            </svg>
                        </div>
                        <input id="search" name="search"
                               class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-amber-500 focus:border-amber-500 sm:text-sm"
                               placeholder="Поиск" type="search">
                    </div>
                </div>
            </div>
            <div class="flex items-center lg:hidden">
                <!-- Mobile menu button -->
                <button type="button"
                        class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-amber-500"
                        aria-controls="mobile-menu" @click="open = !open" aria-expanded="false"
                        x-bind:aria-expanded="open.toString()">
                    <span class="sr-only">Открыть меню</span>
                    <svg x-description="Icon when menu is closed.

Heroicon name: outline/menu" x-state:on="Menu open" x-state:off="Menu closed" class="block h-6 w-6"
                         :class="{ 'hidden': open, 'block': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                    <svg x-description="Icon when menu is open.

Heroicon name: outline/x" x-state:on="Menu open" x-state:off="Menu closed" class="hidden h-6 w-6"
                         :class="{ 'block': open, 'hidden': !(open) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12">
                        </path>
                    </svg>
                </button>
            </div>
            <div class="hidden lg:ml-4 lg:flex lg:items-center">
                <button
                        class="flex-shrink-0 bg-white p-1 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500">
                    <span class="sr-only">Избранное</span>
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                        </path>
                    </svg>
                </button>
                {% if user.is_authenticated %}
                    <!-- Profile dropdown -->
                    <div x-data="{ open: false }" @keydown.escape.stop="open = false" @click.away="open = false"
                         class="ml-4 relative flex-shrink-0">
                        <div>
                            <button type="button"
                                    class="bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500"
                                    id="user-menu" aria-expanded="false" @click="open = !open" aria-haspopup="true"
                                    x-bind:aria-expanded="open">
                                <span class="sr-only">Меню пользователя</span>
                                <img class="h-8 w-8 rounded-full"
                                     src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&amp;ixqx=cII20c177f&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                                     alt="">
                            </button>
                        </div>

                        <transition enter-active-class="transition ease-out duration-100"
                                    enter-class="transform opacity-0 scale-95"
                                    enter-to-class="transform opacity-100 scale-100"
                                    leave-active-class="transition ease-in duration-75"
                                    leave-class="transform opacity-100 scale-100"
                                    leave-to-class="transform opacity-0 scale-95">
                            <div x-description="Dropdown menu, show/hide based on menu state." x-show="open"
                                 class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none"
                                 role="menu" aria-orientation="vertical" aria-labelledby="user-menu">
                                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                   role="menuitem">Профиль</a>
                                <a href="{% url 'account_logout' %}"
                                   class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                                   role="menuitem">Выйти</a>
                            </div>
                        </transition>
                    </div>
                {% else %}

                    <div class="hidden lg:ml-6 lg:flex lg:space-x-8">
                        <a href="{% url 'account_login' %}"
                           class="{% if request.path == '/accounts/login/' %} border-amber-500 text-gray-900 {% else %} border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 {% endif %} inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">
                            Войти
                        </a>
                    </div>

                {% endif %}
            </div>
        </div>
    </div>

    <div x-description="Mobile menu, show/hide based on menu state." class="lg:hidden" id="mobile-menu" x-show="open">
        <div class="pt-2 pb-3 space-y-1">
            <!-- Current: "bg-amber-50 border-amber-500 text-amber-700", Default: "border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800" -->
            <a href="{% url 'excursions:home' %}"
               class="{% if section == "excursions" %}bg-amber-50 border-amber-500 text-amber-600 {% else %} border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 {% endif %} block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Экскурсии</a>
            <a href="{% url 'contacts' %}"
               class="{% if section == "contacts" %}bg-amber-50 border-amber-500 text-amber-600 {% else %} border-transparent text-gray-600 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-800 {% endif %} block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Контакты</a>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full"
                         src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&amp;ixqx=cII20c177f&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=2&amp;w=256&amp;h=256&amp;q=80"
                         alt="">
                </div>
                <div class="ml-3">
                    <div class="text-base font-medium text-gray-800">Том Кук</div>
                    <div class="text-sm font-medium text-gray-500">tom@example.com</div>
                </div>
                <button
                        class="ml-auto flex-shrink-0 bg-white p-1 text-gray-400 rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-500">
                    <span class="sr-only">Избранное</span>
                    <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                        </path>
                    </svg>
                </button>
            </div>
            <div class="mt-3 space-y-1">
                <a href="#"
                   class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">Профиль</a>
                <a href="#"
                   class="block px-4 py-2 text-base font-medium text-gray-500 hover:text-gray-800 hover:bg-gray-100">Выйти</a>
            </div>
        </div>
    </div>
</nav>

templates/partials/navbar.html
<nav class="bg-white shadow" x-data="{mobileOpen:false}">
    <div class="max-w-full mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
                <div class="flex-shrink-0">
                    {% if section == "excursions" %}
                        <img class="block h-12 w-auto" src="/media/img/logo.svg" alt="Я-Евпатория!"/>
                    {% else %}
                        <a href="{% url 'excursions:home' %}" class="focus:outline-none"><img class="block h-12 w-auto"
                                                                                              src="/media/img/logo.svg"
                                                                                              alt="Я-Евпатория!"/></a>
                    {% endif %}
                </div>
                <div class="hidden sm:block sm:ml-12">
                    <div class="flex space-x-4">
                        <a href="{% url 'excursions:home' %}"
                           class="navbar-link {% if section == "excursions" %} active {% else %} non-active {% endif %}">Экскурсии</a>
                        <a href="{% url 'contacts' %}"
                           class="navbar-link {% if section == "contacts" %} active {% else %} non-active {% endif %}">Контакты</a>
                    </div>
                </div>
            </div>
            <div class="hidden sm:ml-6 sm:block">
                <div class="flex items-center">
                    {% comment %} <button class="navbar-button icon">
                        <span class="sr-only">Избранное</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">
                            </path>
                        </svg>
                    </button> {% endcomment %}

                    {% if user.is_authenticated %}

                        <!-- Profile dropdown -->
                        <div class="ml-3 relative" x-data="{isOpen:false}">
                            <div>
                                <button type="button" class="navbar-button user" id="user-menu-button"
                                        aria-expanded="false"
                                        aria-haspopup="true" @click="isOpen = !isOpen" @keydown.escape="isOpen = false">
                                    <span class="sr-only">Open user menu</span>
                                    {% if user.avatar %}
                                        <img class="object-cover h-10 w-10 rounded-full border-2 border-gray-300"
                                             src="{{ user.avatar.url }}"
                                             alt="Avatar">
                                    {% elif user.first_name %}
                                        <div class="h-8 w-8 bg-gray-100 rounded-full text-gray-600 border border-gray-300 shadow flex justify-center items-center overflow-hidden">
                                            <span class="text-base font-semibold">{{ user.first_name|first|upper }}</span>
                                        </div>
                                    {% else %}
                                        <div class="h-8 w-8 bg-gray-100 rounded-full text-gray-600 border border-gray-300 shadow flex justify-center items-center overflow-hidden">
                                            <span class="text-base font-semibold">{{ user.email|first|upper }}</span>
                                        </div>
                                    {% endif %}

                                </button>
                            </div>
                            <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md border border-gray-100 shadow-lg py-1 bg-white"
                                 role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button"
                                 x-show="isOpen"
                                 @click.away="isOpen = false"
                                 x-transition:enter="transition origin-top-right ease-out duration-100"
                                 x-transition:enter-start="opacity-0 transform scale-75"
                                 x-transition:enter-end="opacity-100 transform scale-100"
                                 x-transition:leave="transition origin-top-right ease-in duration-100"
                                 x-transition:leave-start="opacity-100 transform scale-100"
                                 x-transition:leave-end="opacity-0 transform scale-75">
                                <a href="{{ user.get_absolute_url }}" class="navbar-dropdown-item" role="menuitem">Профиль</a>
                                <a href="{% url 'account_logout' %}" class="navbar-dropdown-item"
                                   role="menuitem">Выйти</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="hidden sm:block sm:ml-6">
                            <div class="flex space-x-4">
                                <a href="{% url 'account_login' %}"
                                   class="navbar-link {% if request.path == '/accounts/login/' %} active {% else %} non-active {% endif %}">Войти</a>
                                <a href="{% url 'account_signup' %}"
                                   class="navbar-link sm:hidden md:block {% if request.path == '/accounts/signup/' %} active {% else %} non-active {% endif %}">Регистрация</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="-mr-2 flex sm:hidden">
                <button type="button" class="mobile-menu-button" aria-controls="mobile-menu" aria-expanded="false"
                        @click="mobileOpen = !mobileOpen" @keydown.escape="mobileOpen = false">
                    <span class="sr-only">Меню</span>
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                         stroke="currentColor" aria-hidden="true" x-show="!mobileOpen">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4 6h16M4 12h16M4 18h16"/>
                    </svg>
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                         stroke="currentColor" aria-hidden="true" x-show="mobileOpen">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="sm:hidden" id="mobile-menu" x-show="mobileOpen"
         x-transition:enter="transition origin-top ease-out duration-300"
         x-transition:enter-start="opacity-0 transform -translate-y-6"
         x-transition:enter-end="opacity-100 transform translate-y-0"
         x-transition:leave="transition origin-top ease-in duration-200"
         x-transition:leave-start="opacity-100 transform translate-y-0"
         x-transition:leave-end="opacity-0 transform -translate-y-6" @click.away="mobileOpen = false">
        <div class="px-2 pt-2 pb-3 space-y-1">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="{% url 'excursions:home' %}"
               class="mobile-menu-link {% if section == "excursions" %} active {% else %} non-active {% endif %}">Экскурсии</a>
            <a href="{% url 'contacts' %}"
               class="mobile-menu-link {% if section == "contacts" %} active {% else %} non-active {% endif %}">Контакты</a>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-100">
            {% if user.is_authenticated %}
                <div class="flex items-center px-5">
                    <div class="flex-shrink-0">
                        {% if user.avatar %}
                            <img class="object-cover h-10 w-10 rounded-full border-2 border-gray-300 shadow" src="{{ user.avatar.url }}"
                                 alt="Avatar">
                        {% elif user.first_name %}
                            <div class="h-10 w-10 bg-gray-100 rounded-full text-gray-600 border border-gray-300 shadow flex justify-center items-center overflow-hidden">
                                <span class="text-base font-semibold">{{ user.first_name|first|upper }}</span>
                            </div>
                        {% else %}
                            <div class="h-10 w-10 bg-gray-100 rounded-full text-gray-600 border border-gray-300 shadow flex justify-center items-center overflow-hidden">
                                <span class="text-base font-semibold">{{ user.email|first|upper }}</span>
                            </div>
                        {% endif %}
                    </div>
                    <div class="ml-3">
                        {% if user.first_name %}
                            <div class="text-base font-medium text-gray-600">{{ user.first_name }}</div>
                        {% endif %}
                        <div class="text-sm font-medium text-gray-600">
                            {{ user.email }}
                        </div>
                    </div>
                    {#                    <button class="ml-auto flex-shrink-0 navbar-button icon">#}
                    {#                        <span class="sr-only">Избранное</span>#}
                    {#                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">#}
                    {#                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"#}
                    {#                                  d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z">#}
                    {#                            </path>#}
                    {#                        </svg>#}
                    {#                    </button>#}
                </div>
            {% endif %}
            <div class="mt-3 px-2 space-y-1">
                {% if user.is_authenticated %}
                    <a href="{{ user.get_absolute_url }}" class="mobile-menu-link non-active">Профиль</a>
                    <a href="{% url 'account_logout' %}"
                       class="mobile-menu-link {% if request.path == '/accounts/logout/' %} active {% else %} non-active {% endif %}">Выйти</a>
                {% else %}
                    <a href="{% url 'account_login' %}"
                       class="mobile-menu-link {% if request.path == '/accounts/login/' %} active {% else %} non-active {% endif %}">Войти</a>
                    <a href="{% url 'account_signup' %}"
                       class="mobile-menu-link {% if request.path == '/accounts/signup/' %} active {% else %} non-active {% endif %}">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>