auth1/core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

i_evpatoria/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from excursions.admin import guide_site
from .views import *


urlpatterns = [
    path('', include('excursions.urls', namespace='excursions')),
    path('contacts', contacts, name='contacts'),
    path('users/', include('users.urls', namespace='users')),
    path('superadmin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('guide-admin/', guide_site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
                          
admin.site.index_title = 'Админка'
admin.site.site_header = 'Я-Евпатория!'
admin.site.site_title = 'Я-Евпатория!'

users/urls.py
from django.urls import path
from .views import UserProfileView, UpdateProfileView

app_name = 'users'


urlpatterns = [

    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path('<int:pk>/', UserProfileView.as_view(), name='profile'),
]

auth1/users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(unique=True)

    bio = models.TextField()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

users/models.py
from django.db import models
from django.shortcuts import reverse
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser, BaseUserManager
from PIL import Image
from phonenumber_field.modelfields import PhoneNumberField
from ckeditor_uploader.fields import RichTextUploadingField


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):

    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 3
        if filesize > megabyte_limit * 1024 * 1024:
            raise ValidationError(
                "Максимальный размер файла %s MB" % str(megabyte_limit))

    username = None
    email = models.EmailField(unique=True)

    avatar = models.ImageField(
        upload_to='avatars', max_length=300, validators=[validate_image], blank=True, null=True, verbose_name='Аватар')
    phone = PhoneNumberField(null=True, blank=True, unique=True, verbose_name='Телефон')
    bio = RichTextUploadingField(
        config_name='mini', verbose_name='О себе', blank=True, null=True)
    birthday = models.DateField(
        null=True, blank=True, verbose_name='Дата рожденья')
    guide = models.BooleanField(default=False, verbose_name='Гид')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        SIZE = 500, 500

        if self.avatar:
            pic = Image.open(self.avatar.path)
            if pic.width > 500 or pic.height > 500:
                pic.thumbnail(SIZE, Image.LANCZOS)
                pic.save(self.avatar.path)

users/forms.py
from django import forms
from allauth.account.forms import LoginForm, SignupForm, ChangePasswordForm, ResetPasswordForm, ResetPasswordKeyForm
from ckeditor.fields import RichTextField
from phonenumber_field.formfields import PhoneNumberField
from .models import User


class CustomLoginForm(LoginForm):

    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update({
            'class': 'login-email-field',
            'placeholder': 'Email'
        })
        self.fields['login'].label = "Электронная почта"

        self.fields['password'].widget.attrs.update({
            'class': 'login-password-field'
        })


class CustomSignupForm(SignupForm):

    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class': 'login-email-field',
            'placeholder': 'Email'
        })
        self.fields['email'].label = "Электронная почта"

        self.fields['password1'].widget.attrs.update({
            'class': 'login-password-field'
        })


class CustomChangePasswordForm(ChangePasswordForm):

    def __init__(self, *args, **kwargs):
        super(CustomChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['oldpassword'].widget.attrs.update({
            'class': 'login-email-field',
            'placeholder': 'Текущий пароль'
        })
        # self.fields['email'].label = "Электронная почта"
        #
        self.fields['password1'].widget.attrs.update({
            'class': 'login-password-field'
        })

        self.fields['password2'].widget.attrs.update({
            'class': 'login-password-field'
        })


class CustomResetPasswordForm(ResetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class': 'login-email-field',
            'placeholder': 'Email'
        })
        self.fields['email'].label = "Электронная почта"


class CustomResetPasswordKeyForm(ResetPasswordKeyForm):

    def __init__(self, *args, **kwargs):
        super(CustomResetPasswordKeyForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({
            'class': 'login-password-field'
        })

        self.fields['password2'].widget.attrs.update({
            'class': 'login-password-field'
        })


class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "avatar",
        )


class UpdateGuideProfileForm(forms.ModelForm):
    class Meta:
        model = User
        bio = RichTextField()
        phone = PhoneNumberField()
        fields = (
            "first_name",
            "last_name",
            "bio",
            "avatar",
            "phone",
        )

auth1/users/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django import forms as d_forms
from . import models, forms


class UserProfileView(LoginRequiredMixin, DetailView):
    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    success_message = "Профиль обновлён."

    def get_object(self, queryset=None):
        return self.request.user

    def get_form_class(self):
        if self.request.user.guide:
            return forms.UpdateGuideProfileForm
        else:
            return forms.UpdateUserProfileForm

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)

        if not self.request.user.guide:
            form.fields["first_name"].widget.attrs = {"placeholder": "Имя", "class": "update-input"}
            form.fields["last_name"].widget.attrs = {"placeholder": "Фамилия", "class": "update-input"}
        else:
            form.fields["first_name"].widget.attrs = {"placeholder": "Имя", "class": "update-input"}
            form.fields["last_name"].widget.attrs = {"placeholder": "Фамилия", "class": "update-input"}
            form.fields["bio"].widget.attrs = {"placeholder": "О себе", "class": "update-input"}
            form.fields["phone"].widget.attrs = {"placeholder": "Телефон: +79780000000", "class": "update-input"}
        return form

templates/users/update-profile.html
{% extends "base.html" %}

{% load static %}

{% block title %}Изменить профиль | {% endblock %}

{% block content %}

    <div class="min-h-full flex flex-col py-8 lg:py-12 sm:px-6 lg:px-8">

        <div class="sm:mx-auto sm:w-full sm:max-w-md">
            <h2 class="mt-6 text-center text-3xl font-bold text-gray-700">Изменить профиль</h2>
        </div>
        <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
            <div class=" flex flex-col items-center bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
                {% if user.avatar %}
                    <div class="h-36 w-36 rounded-full bg-cover border-2 border-gray-300 shadow"
                         style="background-image: url({{ user.avatar.url }});">
                    </div>
                {% elif user.first_name %}
                    <div class="h-20 w-20 bg-gray-100 rounded-full text-gray-600 font-semibold border-2 border-gray-300 shadow flex justify-center items-center overflow-hidden">
                        <span class="text-5xl">{{ user.first_name|first|upper }}</span>
                    </div>
                {% else %}
                    <div class="h-20 w-20 bg-gray-100 rounded-full text-gray-600 font-semibold border-2 border-gray-300 shadow flex justify-center items-center overflow-hidden">
                        <span class="text-5xl">{{ user.email|first|upper }}</span>
                    </div>
                {% endif %}

                {% include 'mixins/form/update-form.html' with form=form  %}
                <a href="{% url 'account_change_password' %}" class="py-2 mt-6 font-medium text-amber-600 hover:text-amber-500 focus:outline-none focus:text-amber-500">Изменить пароль</a>
            </div>
        </div>
    </div>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

templates/users/user_detail.html
{% extends "base.html" %}



{% block title %}Профиль | {% endblock %}

{% block content %}

    <div class="min-h-full flex flex-col py-8 lg:py-12 sm:px-6 lg:px-8">

        <div class="sm:mx-auto sm:w-full sm:max-w-md">
            <h2 class="mt-6 text-center text-3xl font-bold text-gray-700">Профиль</h2>
        </div>
        <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
            <div class=" flex flex-col items-center bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
                {% if user_obj.avatar %}
                    <div class="h-36 w-36 mb-5 rounded-full bg-cover border-2 border-gray-300 shadow"
                         style="background-image: url({{ user_obj.avatar.url }});">
                    </div>
                {% elif user_obj.first_name %}
                    <div class="h-20 w-20 mb-5 bg-gray-100 rounded-full text-gray-600 font-semibold border-2 border-gray-300 shadow flex justify-center items-center overflow-hidden">
                        <span class="text-5xl">{{ user_obj.first_name|first|upper }}</span>
                    </div>
                {% else %}
                    <div class="h-20 w-20 mb-5 bg-gray-100 rounded-full text-gray-600 font-semibold border-2 border-gray-300 shadow flex justify-center items-center overflow-hidden">
                        <span class="text-5xl">{{ user_obj.email|first|upper }}</span>
                    </div>
                {% endif %}
                {% if user_obj.first_name and user_obj.last_name %}
                    <div class="text-xl font-bold text-gray-700 mb-5">
                        {{ user_obj.first_name }} {{ user_obj.last_name }}
                    </div>
                {% elif user_obj.first_name %}
                    <div class="text-xl font-bold text-gray-700 mb-5">
                        {{ user_obj.first_name }}
                    </div>
                {% endif %}
                {% if user_obj.guide and user_obj.bio %}
                    <div class="text-sm font-medium text-gray-700 w-full mb-5">
                        {{ user_obj.bio|safe }}
                    </div>
                {% endif %}
                {% if user_obj.guide and user_obj.phone %}
                    <div class="text-xl font-semibold text-gray-700 mb-5">
                        <p class="text-base text-gray-600 text-center mt-3">Телефон</p>
                        <p class="text-xl font-bold text-gray-700 text-center mt-2">
                            <a href=”tel:{{ user_obj.phone }}” class="sm:hidden">{{ user_obj.phone.as_international }}</a>
                            <span class="hidden sm:inline">{{ user_obj.phone.as_international }}</span>
                        </p>
                    </div>
                {% endif %}
                {% if user == user_obj %}
                    <a href="{% url 'users:update' %}"
                       class="w-full flex justify-center mt-5 py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-amber-500 hover:bg-amber-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-amber-400">Изменить
                        профиль</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}